<?php

	// Allways takes a map id as first parameter (only used as base config if a second parameter is given). 
	// If a second parameter is given then it must be set to a basic group target array or null.
	// If a third parameter is given then it must be set to a basic layer target array.
	// Prints a form with a button labeled "Förhandsgranska" as only visible element. 
	// The button opens a new browser tab/window with an Origo map generated by writeConfig.php.
	// The map will show a preview of a map, a group or a layer depending on the input parameters.
	function printConfigPreviewButton($mapId, $group=null, $layer=null)
	{
		$groupInput='';
		$layerInput='';
		if (isset($group))
		{
			$groupInput="<input type='hidden' name='group' value='$group'>";
		}
		if (isset($layer))
		{
			$layerInput="<input type='hidden' name='layer' value='$layer'>";
		}
		echo <<<HERE
			<form action="writeConfig.php" method="get" target="_blank">
				<input type="hidden" name="getHtml" value="y">
				{$groupInput}
				{$layerInput}
				<button class="updateButton" type="submit" name="map" value="{$mapId}">
					Förhandsgranska
				</button>
			</form>
		HERE;
	}

?>
